# -*- coding: utf-8 -*-
"""chat_bot_flask.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1juIa6GptTBm6ATlRZ_Uwq41Yl4jEuC1f
"""

from flask import Flask, request, jsonify
from openai import OpenAI
import os

app = Flask(__name__)

client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=os.environ.get("OPENROUTER_API_KEY")
)

MODELO = "openai/gpt-4o-mini"

@app.route("/")
def home():
    return "Chatbot Online"

@app.route("/chat", methods=["POST"])
def chat():
    dados = request.get_json()

    pergunta = dados.get("pergunta", "")

    resposta = client.chat.completions.create(
        model=MODELO,
        messages=[
            {
                "role": "user",
                "content": pergunta
            }
        ]
    )

    texto = resposta.choices[0].message.content

    return jsonify({
        "resposta": texto
    })

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)